sudo: required
services:
  - docker

before_install:
  - docker build -t arbiani/docker-react -f Dockerfile.dev .

script:
  - docker run arbiani/docker-react npm run test -- --coverage
  

deploy:
  provider: elastisbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-573883188984"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"